apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
        - name: inventoryservice
          image: inventoryservice:latest   # <-- make sure you build with this tag
          imagePullPolicy: IfNotPresent    # <-- use local image if available
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver;Database=OrdersDb;User Id=sa;Password=123456Hi;TrustServerCertificate=True;"
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081   # <-- access at http://localhost:30081
  selector:
    app: inventoryservice
