apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: orderservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver,1433;Database=OrdersDb;User Id=sa;Password=123456Hi;TrustServerCertificate=True"

            - name: InventoryService__Url
              value: "http://inventoryservice:8080"
            - name: RabbitMq__Host
              value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: NodePort
  selector:
    app: orderservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
