apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'orderservice'
        static_configs:
          - targets: ['orderservice:8080']
      - job_name: 'inventoryservice'
        static_configs:
          - targets: ['inventoryservice:8080']
