apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31433   # Expose SQL Server on 31433
  selector:
    app: sqlserver
